### ISSUE TITLE
Update to PHP8+

### ISSUE THREAD

**Issue by MarcHagen** [WyriHaximus/reactphp-psr-3-stdio#38]
Currently this library is not compatible with the new PHP8+.
Is there any intention to make this compatible with the new versions ?

**Comment by WyriHaximus** [comment]
Yes, been working on my other PSR-3 packages and once those are upgraded to support PHP 8 this one will be next.

**Comment by MarcHagen** [comment]
Good stuff! I'll wait for the update :)

**Comment by WyriHaximus** [comment]
[`v3.0.0`](https://github.com/WyriHaximus/reactphp-psr-3-stdio/releases/tag/3.0.0) is now out and only supports 8+

**Comment by MarcHagen** [comment]
Good stuff! Thank you very much, will begin testing/implementing 🙏

**Comment by WyriHaximus** [comment]
Let me know if you run into anything. API wise it should be fully compatible with v2 so if you have to support PHP 7 you can always do `^2 || ^1.2` in your `composer.json`.

**Comment by MarcHagen** [comment]
Cool, will let you know if I have something.
The project I'm working on is only 8.1+ so I'm "pushing" packages to update because of dependencies. So far all looks good 👍🏻.

**Comment by WyriHaximus** [comment]
Working on the same, updating all my projects to 8.1 and as such updating any and all packages I have to 8.1 (or 8+ if possible) in the order composer complains about it :smile: .
