### ISSUE TITLE
Channel name/Timestamp support

### ISSUE THREAD

**Issue by cdosoftei** [WyriHaximus/reactphp-psr-3-stdio#41]
Hi @WyriHaximus :wave: -- thanks for open sourcing this project!

Would you consider adding the notion of channel names (a la [Monolog](https://github.com/Seldaek/monolog/blob/fb2c324c17941ffe805aa7c953895af96840d0c9/src/Monolog/Logger.php#L153)), effectively acting as a prefix to the log entry's level?

It doesn't have to be disruptive, it can be implemented as a `withChannelName()` method, in the same spirit as `withNewLine()` for example.

Happy to propose a pull request if you think it's a good idea.

_Update:_ a `withTimestamp()` method would be helpful too. It could take a timezone parameter (default to `UTC`) and perhaps a format parameter (default to ISO 8601 format), although these days modern applications make those timezone and formatting assumptions anyway :wink:

**Comment by WyriHaximus** [comment]
Hey @cdosoftei :wave: 

I'd be open to having those features PRed to this project as something that can be optionally enabled.

Alternatively, you can use Monolog and use this handler with the `PsrHandler` that monolog provides. I'm fine with both :smiley:

**Comment by cdosoftei** [comment]
Hey @WyriHaximus -- having just now realized the `PsrHandler` utilization pattern, I'll go ahead and close this ticket. I was contemplating replacing Monolog with this library when in reality I just had to swap `StreamHandler` (the blocking component) in favour of `PsrHandler(StdioLogger::create())`. It's working like a charm, thanks!

**Comment by WyriHaximus** [comment]
@cdosoftei You're welcome! I'm using exactly that setup myself, maybe the readme should contain that example? :thinking:
